export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const UPDATE_USERID_NAME = 'UPDATE_USERID_NAME';

export const SET_USERNAME_EMAIL = 'SET_USERNAME_EMAIL';
export const GET_USERNAME_EMAIL = 'GET_USERNAME_EMAIL';

export const START_LOADING_TOURNEYS = 'START_LOADING_TOURNEYS';
export const FINISH_LOADING_TOURNEYS = 'FINISH_LOADING_TOURNEYS';
export const GET_TOURNEYS = 'GET_TOURNEYS';
export const GET_MY_TOURNEYS = 'GET_MY_TOURNEYS';
export const RETURN_TOURNEYS = 'RETURN_TOURNEYS';
export const RETURN_MY_TOURNEYS = 'RETURN_MY_TOURNEYS';

export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';
export const EMPTY_PRODUCT_LIST = 'EMPTY_PRODUCT_LIST';
