import React, {Component} from 'react';
import './home.css';
import winMoneyImg from "../../assets/winMoney.jpg";
import hostTourneyImg from "../../assets/hostTourneyImg.jpg";

class Home extends Component {
    
    render () {
        
        return (
            <div>
                <div className="homeDiv">
                    <div className="homeSubDiv">
                        <h1 className="homeMainHead">Crypto Tourneys</h1>
                        <button>Coming Soon!</button>
                        <h2>The ONLY place for crypto trading tournaments!</h2>
                            <div className="infoDiv">
                                <h3>WIN BTC!</h3>
                                <p>Compete in trading tournaments to win BTC prizes!</p>
                                <h3>EARN BTC!</h3>
                                <p>Host your own trading tournaments and get a share of the entry fees!</p>
                                <h3>PROVE YOUR SKILLS!</h3>
                                <p>Prove your trading skills to your followers by getting onto our leaderboard!</p>
                            </div>
                    </div>
                </div>
                <div className="homeDiv2">
                    <div className="homeLowerSubDivWrapper">
                        <div className="homeLowerSubDiv">
                            <h2>Compete in Trading Tournaments</h2>
                            <img className="winMoneyImg" src={winMoneyImg} />
                            <p>Compete in cryptocurrency trading tournaments and WIN PRIZES by out trading the competition!</p>
                            <p>We have tournaments constantly running on some of the largest and most reputable crypto exchanges!</p>
                            <p>Link your exchange API key and our software analyses your trades and calculates your trading profit!</p>
                            <p>Filter tournaments by entry fee, number of entrants, exchange used, trading products and more!</p>
                        </div>
                        <div className="homeLowerSubDiv">
                            <h2>Host Your Own Tournaments</h2>
                            <img className="hostTourneyImg" src={hostTourneyImg} />
                            <p>EARN MONEY by hosting your own custom trading tournaments!</p>
                            <p>Select the exchange to trade on, the trading products allowed for the tournament (e.g. BTCUSD), entry fee, duration, maximum number of entrants and more!</p>
                            <p>Make the tournament private and only invite your friends or make it public for anyone in the world to enter!</p>
                            <p>You receive up to 50% of the fees generated by the tournament!</p>
                        </div>
                    </div>
                </div>
            </div>
        );       
    }
}

export default Home;