"""empty message

Revision ID: 83d309483d52
Revises: 
Create Date: 2020-08-29 18:24:06.498888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d309483d52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('productList',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.Column('baseCurrency', sa.String(length=16), nullable=True),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('trades',
    sa.Column('tradeId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tradeId')
    )
    op.create_table('usernames',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('accountBalances',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('activeTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('completedEntrants',
    sa.Column('entrantId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('totalInvested', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('entrantId')
    )
    op.create_table('completedTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('depositWithdrawHistory',
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('txHash', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('noConfirmations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('transactionId')
    )
    op.create_table('registrationTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.Column('payoutStruct', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('userAPI',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('FTXKey', sa.String(length=50), nullable=True),
    sa.Column('FTXSecret', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('activeEntrants',
    sa.Column('entrantId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('totalInvested', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activeTourneys.tourneyId'], ),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('entrantId')
    )
    op.create_table('activeProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activeTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('completedProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['completedTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('entrants',
    sa.Column('entrantId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationTourneys.tourneyId'], ),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('entrantId')
    )
    op.create_table('registeringProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('tourneyInvites',
    sa.Column('inviteId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('inviteId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourneyInvites')
    op.drop_table('registeringProducts')
    op.drop_table('entrants')
    op.drop_table('completedProducts')
    op.drop_table('activeProducts')
    op.drop_table('activeEntrants')
    op.drop_table('userAPI')
    op.drop_table('registrationTourneys')
    op.drop_table('depositWithdrawHistory')
    op.drop_table('completedTourneys')
    op.drop_table('completedEntrants')
    op.drop_table('activeTourneys')
    op.drop_table('accountBalances')
    op.drop_table('usernames')
    op.drop_table('trades')
    op.drop_table('productList')
    op.drop_table('allTourneys')
    # ### end Alembic commands ###
