"""empty message

Revision ID: 9bf03b70ff73
Revises: 83d309483d52
Create Date: 2020-08-30 23:33:45.934147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bf03b70ff73'
down_revision = '83d309483d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('productList',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.Column('baseCurrency', sa.String(length=16), nullable=True),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('accountBalances',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('activeTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.Column('payoutStruct', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('completedEntrants',
    sa.Column('entrantId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('totalInvested', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('entrantId')
    )
    op.create_table('completedTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.Column('payoutStruct', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('depositWithdrawHistory',
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('txHash', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('noConfirmations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('transactionId')
    )
    op.create_table('registrationTourneys',
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('hostId', sa.String(length=50), nullable=False),
    sa.Column('maxEntrants', sa.Integer(), nullable=False),
    sa.Column('minEntrants', sa.Integer(), nullable=False),
    sa.Column('noEntrants', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('startTime', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('endTime', sa.String(length=16), nullable=False),
    sa.Column('startTS', sa.Integer(), nullable=False),
    sa.Column('endTS', sa.Integer(), nullable=False),
    sa.Column('quoteCurrency', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('entryFee', sa.Float(), nullable=False),
    sa.Column('payoutStruct', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('tourneyId')
    )
    op.create_table('userAPI',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('FTXKey', sa.String(length=50), nullable=True),
    sa.Column('FTXSecret', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('activeEntrants',
    sa.Column('entrantId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('totalInvested', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activeTourneys.tourneyId'], ),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], ),
    sa.PrimaryKeyConstraint('entrantId')
    )
    op.create_table('activeProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activeTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('completedProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['completedTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('registeringProducts',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('productType', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('tourneyInvites',
    sa.Column('inviteId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('tourneyId', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationTourneys.tourneyId'], ),
    sa.PrimaryKeyConstraint('inviteId')
    )
    op.drop_table('completedproducts')
    op.drop_table('activeproducts')
    op.drop_table('activeentrants')
    op.drop_table('activetourneys')
    op.drop_table('accountbalances')
    op.drop_table('completedentrants')
    op.drop_table('registrationtourneys')
    op.drop_table('completedtourneys')
    op.drop_table('alltourneys')
    op.drop_table('userapi')
    op.drop_table('registeringproducts')
    op.drop_table('depositwithdrawhistory')
    op.drop_table('tourneyinvites')
    op.drop_table('productlist')
    op.drop_constraint('entrants_ibfk_1', 'entrants', type_='foreignkey')
    op.create_foreign_key(None, 'entrants', 'registrationTourneys', ['tourneyId'], ['tourneyId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entrants', type_='foreignkey')
    op.create_foreign_key('entrants_ibfk_1', 'entrants', 'registrationtourneys', ['tourneyId'], ['tourneyId'])
    op.create_table('productlist',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exchange', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('productType', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('baseCurrency', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('quoteCurrency', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tourneyinvites',
    sa.Column('inviteId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationtourneys.tourneyId'], name='tourneyinvites_ibfk_1'),
    sa.PrimaryKeyConstraint('inviteId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('depositwithdrawhistory',
    sa.Column('transactionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', mysql.FLOAT(), nullable=False),
    sa.Column('txHash', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('noConfirmations', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], name='depositwithdrawhistory_ibfk_1'),
    sa.PrimaryKeyConstraint('transactionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registeringproducts',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('exchange', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('productType', mysql.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['registrationtourneys.tourneyId'], name='registeringproducts_ibfk_1'),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userapi',
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('FTXKey', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('FTXSecret', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], name='userapi_ibfk_1'),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alltourneys',
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('hostId', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tourneyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('completedtourneys',
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hostId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('minEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maxEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('noEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quoteCurrency', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('entryFee', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], name='completedtourneys_ibfk_1'),
    sa.PrimaryKeyConstraint('tourneyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registrationtourneys',
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hostId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('maxEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('noEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quoteCurrency', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('visibility', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('entryFee', mysql.FLOAT(), nullable=False),
    sa.Column('payoutStruct', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], name='registrationtourneys_ibfk_1'),
    sa.PrimaryKeyConstraint('tourneyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('completedentrants',
    sa.Column('entrantId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('totalInvested', mysql.FLOAT(), nullable=False),
    sa.Column('totalValue', mysql.FLOAT(), nullable=False),
    sa.Column('profit', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], name='completedentrants_ibfk_1'),
    sa.PrimaryKeyConstraint('entrantId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accountbalances',
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('balance', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], name='accountbalances_ibfk_1'),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activetourneys',
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hostId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('minEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maxEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('noEntrants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endDate', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('endTime', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('startTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endTS', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('quoteCurrency', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('visibility', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('entryFee', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['usernames.userId'], name='activetourneys_ibfk_1'),
    sa.PrimaryKeyConstraint('tourneyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activeentrants',
    sa.Column('entrantId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('totalInvested', mysql.FLOAT(), nullable=False),
    sa.Column('totalValue', mysql.FLOAT(), nullable=False),
    sa.Column('profit', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activetourneys.tourneyId'], name='activeentrants_ibfk_1'),
    sa.ForeignKeyConstraint(['userId'], ['usernames.userId'], name='activeentrants_ibfk_2'),
    sa.PrimaryKeyConstraint('entrantId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activeproducts',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('exchange', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('productType', mysql.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['activetourneys.tourneyId'], name='activeproducts_ibfk_1'),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('completedproducts',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tourneyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('exchange', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('productType', mysql.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tourneyId'], ['completedtourneys.tourneyId'], name='completedproducts_ibfk_1'),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tourneyInvites')
    op.drop_table('registeringProducts')
    op.drop_table('completedProducts')
    op.drop_table('activeProducts')
    op.drop_table('activeEntrants')
    op.drop_table('userAPI')
    op.drop_table('registrationTourneys')
    op.drop_table('depositWithdrawHistory')
    op.drop_table('completedTourneys')
    op.drop_table('completedEntrants')
    op.drop_table('activeTourneys')
    op.drop_table('accountBalances')
    op.drop_table('productList')
    op.drop_table('allTourneys')
    # ### end Alembic commands ###
